baseURL = "https://www.ourlockdown.co.uk/"
disqusShortname = ""
languageCode = "en-gb"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Welcome to Happy Hoppers School!"
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = ""
description = "Our Lockdown"
enableRobotsTXT = "true"
google_analitycs_id = "UA-163798072-1"
google_tag_manager = "GTM-PN49BWX"
logo = "images/lockdownlogo.jpg"
social = []
[params.banner]
bgImage = "images/banner-bg.svg"
image = "images/whatsapp-image-2020-11-12-at-17-33-23.jpeg"
title = "Welcome to the Happy Hoppers School 2021!"
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
